colSchema <-
  cols_only(
    `store #`                  = col_double(),
    `%black`                   = col_double(),
    `%spanishsp`               = col_double(),
    `%inc0-10`                 = col_double(),
    `%inc10-14`                = col_double(),
    `%inc14-20`                = col_double(),
    `%inc20-30`                = col_double(),
    `%inc30-50`                = col_double(),
    `%inc50-100`               = col_double(),
    `%inc100+`                 = col_double(),
    `medianinc`                = col_integer(),
    `medianrent`               = col_integer(),
    `medianhome`               = col_integer(),
    `%owners`                  = col_double(),
    `%nocars`                  = col_double(),
    `%1car`                    = col_double(),
    `%tvs`                     = col_double(),
    `%washers`                 = col_double(),
    `%dryers`                  = col_double(),
    `%dishw`                   = col_double(),
    `%aircond`                 = col_double(),
    `%freezer`                 = col_double(),
    `%sechome`                 = col_double(),
    `%sch0-8`                  = col_double(),
    `%sch9-11`                 = col_double(),
    `%sch12`                   = col_double(),
    `%sch12+`                  = col_double(),
    `population`               = col_integer(),
    `familysize`               = col_double(),
    `selling_sqrft (in 1000s)` = col_double(),
    `sales (in $1000s)`        = col_double(),
    `percent_hard_goods`       = col_double(),
    `comtype`                  = col_factor(levels = c(1,2,3,4,5,6,7), ordered = FALSE)
  )

colNames <-
  c(
    "storeId",
    "black",
    "spanishsp",
    "inc0_10",
    "inc10_14",
    "inc14_20",
    "inc20_30",
    "inc30_50",
    "inc50_100",
    "inc100Plus",
    "medianInc",
    "medianRent",
    "medianHome",
    "owners",
    "nocars",
    "car1",
    "tvs",
    "washers",
    "dryers",
    "dishw",
    "aircond",
    "freezer",
    "secHome",
    "sch0_8",
    "sch9_11",
    "sch12",
    "sch12Plus",
    "population",
    "familySize",
    "sellingSqrft",
    "sales",
    "percentHardGoods",
    "comType"
  )
